import Head from "next/head";
import { useRouter } from "next/router";
import FilmDetails from "../../components/FilmDetails";
import Footer from "../../components/Footer";
import Navigation from "../../components/navigation/Navigation";

const films = () => {
  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <FilmDetails />
        <Footer />
      </main>
    </>
  );
};

export default films;
