import Head from "next/head";
import FilmSection from "../../components/MainSection";
import Footer from "../../components/Footer";
import Navigation from "../../components/navigation/Navigation";
import LoginSection from "../../components/login/LoginSection";
import RegisterSection from "../../components/login/RegisterSection";
import MainLoginSection from "../../components/login/MainLoginPanel";

export default function signIn() {
  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <MainLoginSection />
        <Footer />
      </main>
    </>
  );
}
