import Head from "next/head";
import AddPlan from "../../../components/AddPlan";
import Navigation from "../../../components/navigation/Navigation";

export default function details() {
  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <AddPlan />
      </main>
    </>
  );
}
