import Head from "next/head";
import { useRouter } from "next/router";
import Footer from "../../components/Footer";
import Navigation from "../../components/navigation/Navigation";
import SeriesDetails from "../../components/SeriesDetails";

const series = () => {
  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <SeriesDetails />
      </main>
    </>
  );
};

export default series;
