import Head from "next/head";
import Navigation from "../../components/Navigation";
import FilmSection from "../../components/FilmSection";

export default function films() {
  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <FilmSection />
      </main>
    </>
  );
}
