import Head from "next/head";
import Navigation from "../../components/navigation/Navigation";
import Footer from "../../components/Footer";
import FilterPage from "../../components/filter/FilterPage";

import { gql } from "@apollo/client";
import { client } from "../../lib/apolloClient";

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Query {
        getFilms {
          id
          title
          description
          director
          scenario
          genre
          production
          premiere
          miniature
          content
          duration
          like
          dislike
          type
          platforms
        }
        getSeries {
          id
          title
          description
          director
          scenario
          genre
          production
          premiere
          miniature
          duration
          like
          dislike
          type
          platforms
        }
      }
    `,
  });

  let films = data.getFilms;
  let series = data.getSeries;

  let both = films
    .concat(series)
    .slice()
    .sort((a, b) => b.like - a.like);
  return {
    props: {
      data: both,
    },
  };
}

export default function categories({ data }) {
  const submitHandler = () => {};

  return (
    <>
      <Head>
        <title>FilmInc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <FilterPage data={data} />
        <Footer />
      </main>
    </>
  );
}
